name: 'additional_files'

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  additional_files:
    name: additional_files
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ${{ github.actor == 'dependabot[bot]' && fromJSON('["ubuntu-latest"]') || fromJSON('["ubuntu-latest", "macos-latest"]') }}

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Run ShellCheck
      uses: ./
      id: check
      with:
        additional_files: run finish discovery
        ignore_paths: ignore
        scandir: testfiles

    - name: Verify check
      run: | 
        expect="testfiles/scandir/run"

        if [[ ! "${{ steps.check.outputs.files }}" =~ testfiles/scandir/run ]];then
          echo "::error:: Expected file testfiles/scandir/run not found in ${{ steps.check.outputs.files }}"
          exit 1
        elif [[ ! "${{ steps.check.outputs.files }}" =~ testfiles/scandir/finish ]];then
          echo "::error:: Expected file testfiles/scandir/finish not found in ${{ steps.check.outputs.files }}"
          exit 1
        elif [[ ! "${{ steps.check.outputs.files }}" =~ testfiles/scandir/discovery ]];then
          echo "::error:: Expected file testfiles/scandir/discovery not found in ${{ steps.check.outputs.files }}"
          exit 1
        fi 