name: 'ignore_names'

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  ignore_names:
    name: ignore_names
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ${{ github.actor == 'dependabot[bot]' && fromJSON('["ubuntu-latest"]') || fromJSON('["ubuntu-latest", "macos-latest"]') }}

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Run ShellCheck
      uses: ./
      id: check
      with:
        ignore_paths: ignore
        ignore_names: ignore_single_file.sh

    - name: Verify check
      run: | 
        expect="testfiles/test.bash"
        notexpect="testfiles/ignore_single_file.sh"

        if [[ ! "${{ steps.check.outputs.files }}" =~ $expect ]];then
          echo "::error:: Expected file $expect not found in ${{ steps.check.outputs.files }}"
          exit 1
        elif [[ "${{ steps.check.outputs.files }}" =~ $notexpect ]];then
          echo "::error:: Expected file $notexpect found in ${{ steps.check.outputs.files }}"
          exit 1
        fi 
